### ISSUE TITLE
Cleanup Command

### ISSUE THREAD

**Issue by m1guelpf** [clarkeash/doorman#10]
Add an artisan command to remove expired invites from the database. I can do it if you want.

**Comment by clarkeash** [comment]
I'd be happy to add this, you are welcome to do the work. Happy to help if you need any assistance.

**Comment by m1guelpf** [comment]
@clarkeash Would this work?
``` php
use Clarkeash\Doorman\Models\Invite;

public function handle()
{
Invite::useless()->delete();
}
```

**Comment by clarkeash** [comment]
why not do something along the lines of:

```php
Invite::where('valid_until', '<', Carbon::now())->delete();
```

**Comment by m1guelpf** [comment]
@clarkeash That doesn't cover the max uses reached case. I would move the is_expired logic to the expired property (#12)

**Comment by clarkeash** [comment]
I have added some [query scopes](https://laravel.com/docs/5.4/eloquent#local-scopes) to the Invite model.

* `Invite::expired()` - return all expired invites.
* `Invite::full()` - return all full (max uses reached) invites.
* `Invite::useless()` - return all expired and full invites.

Now you can just do:

```php
Invite::useless()->delete();
```

to remove useless invites from the database.
