### ISSUE TITLE
Add an expired function to the model

### ISSUE THREAD

**Issue by m1guelpf** [clarkeash/doorman#12]
It would be cool (and very useful to #10) to have an `setExpiredAttribute()` function on the Invite model, so you can do $invite->expired and get a boolean

**Comment by clarkeash** [comment]
how would you use this in #10 ?

**Comment by m1guelpf** [comment]
@clarkeash Commented #10 code, now you can see it.

**Comment by m1guelpf** [comment]
@clarkeash Would this work?
``` php
use Carbon\Carbon;
public function setExpiredAttribute()
{
return $this->getAttribute('valid_until') > Carbon::now() && $this->getAttribute('max') => $this->getAttribute('uses');
}
```

**Comment by clarkeash** [comment]
I have added a few helper methods to the model:

* `hasExpired()`
* `isFull()`
* `isRestricted()`
* `isRestrictedFor($email)`
* `isUseless()` - is full or expired.
