### ISSUE TITLE
Make email addresses case-insensitive

### ISSUE THREAD

**Issue by nexxai** [clarkeash/doorman#27]
I'm sure this is probably a quick fix but is it possible to use strtolower() on the email addresses so that if someone originally provides "THISISATEST@TEST.COM" as their email address, but then tries to register with "thisisatest@test.com", it will accept the invite code anyways?  As it stands, that doesn't currently happen.

**Comment by clarkeash** [comment]
I will get to this just not had chance yet. 👍

**Comment by clarkeash** [comment]
Hey, this is fixed. Sorry it took so long I havent had much time to work on open source lately.
I should be tagging 2.0 later today with this fix in (will require laravel 5.6 and php 7.1)
