### ISSUE TITLE
Case sensitivity problem

### ISSUE THREAD

**Issue by TNovalis** [clarkeash/doorman#34]
My invite codes are always returning as invalid, I think this is due to when the code is being generated, it is mixed case and when it is check it is forced to be uppercase.

[Generation](https://github.com/clarkeash/doorman/blob/master/src/Drivers/BasicDriver.php#L17)
[Saving](https://github.com/clarkeash/doorman/blob/master/src/Generator.php#L94-L125)
[Validation](https://github.com/clarkeash/doorman/blob/master/src/Doorman.php#L74)

All I'm using is the built in form validation and the basic driver from doorman.

**Comment by clarkeash** [comment]
Hey @TNovalis sorry this took so long, not had chance to work on it until now. But this should be fixed in v2.1.1
