### ISSUE TITLE
Laravel 5.7 Compatibility

### ISSUE THREAD

**Issue by wyoumans** [clarkeash/doorman#35]

**Comment by clarkeash** [comment]
Updated laravel and test bench

**Comment by clarkeash** [comment]
First problem (mockery no longer installed by default)


<img width="1102" alt="screenshot 2018-10-06 at 20 16 53" src="https://user-images.githubusercontent.com/1612186/46574655-eba4cb80-c9a6-11e8-931d-f3fad22bd67b.png">

**Comment by clarkeash** [comment]
2nd issue (looks like some timing precision has changed):

<img width="1792" alt="screenshot 2018-10-06 at 20 31 40" src="https://user-images.githubusercontent.com/1612186/46574671-37f00b80-c9a7-11e8-96af-46af13673992.png">

**Comment by clarkeash** [comment]
Okay, this is now working:

I am not overly found of the solution: `$date = Carbon::now( 'UTC')->endOfDay()->startOfSecond();` add this `startOfSecond()` call feels a bit weird.

But tests are green:

<img width="948" alt="screenshot 2018-10-06 at 20 57 21" src="https://user-images.githubusercontent.com/1612186/46574860-99fe4000-c9aa-11e8-9f98-547058785f06.png">

**Comment by clarkeash** [comment]
New issue: `startOfSecond()` doesnt exist in whatever version of Carbon ships with laravel 5.6

<img width="870" alt="screenshot 2018-10-06 at 21 02 49" src="https://user-images.githubusercontent.com/1612186/46574898-42ac9f80-c9ab-11e8-8b05-a333c6644d36.png">

**Comment by clarkeash** [comment]
Solved:

<img width="1041" alt="screenshot 2018-10-06 at 21 12 08" src="https://user-images.githubusercontent.com/1612186/46574959-848a1580-c9ac-11e8-9121-d0f4568387c1.png">

will tag v2.1.0

**Comment by clarkeash** [comment]
https://github.com/clarkeash/doorman/releases/tag/v2.1.0

**Comment by wyoumans** [comment]
Thanks a lot for your time. Really appreciate it.

**Comment by clarkeash** [comment]
No problem 😄
