### ISSUE TITLE
publish prefixes

### ISSUE THREAD

**Issue by tillkruss** [clarkeash/doorman#40]
What's the reason for not prefixing the assets?

`doorman-config` would be much clearer.

<img width="292" alt="Screen Shot 2019-04-22 at 11 50 59 AM" src="https://user-images.githubusercontent.com/665029/56518687-ef3c1200-64f4-11e9-8e32-a9cbab6964ca.png">

**Comment by clarkeash** [comment]
There was no reason, not sure the prefixes were quite as common 2 years ago. More than happy to change it 😄

**Comment by tillkruss** [comment]
That would be amazing, thanks!

**Comment by clarkeash** [comment]
@tillkruss sorry forgot about this, will take a look soon.
