### ISSUE TITLE
Invite codes for models

### ISSUE THREAD

**Issue by GreenImp** [clarkeash/doorman#43]
Hi,
Instead of requiring invite codes to register on my website, I'm wanting to allow users to invite users to "access" a particular model.

For example, I have User 1, who "owns" a group model on the site.
User 1 wants some members in their group, so they send an invite to user2@users.com, so that user can then use the invite to join the group.

Would this library work with the idea of having an invite linked to an eloquent model, rather than the site registration form? I'm not expecting it to add them to the group, just the validation side of things to ensure that the invite is valid for the group.

**Comment by clarkeash** [comment]
The migrations set the email address to be unique so you wouldnt be able to have 2 invites with the same email, so you wouldnt be able to invite a user to multiple groups.

**Comment by clarkeash** [comment]
I guess if you had a **groups** table you could also have a **group_invite** table and then you could do something like `$group->invite->where(...)` but it may be easier not to use this library, as you will have to do most the work yourself.
