### ISSUE TITLE
Bounced Email

### ISSUE THREAD

**Issue by jasperf** [clarkeash/doorman#53]
Is there a way to show the email bounced via Doorman? Or would I need to load this data from our third party email provider Sendgrid? Two, I removed the invite and re-added it again with same email address once the email address was actually added and working.  But then no email was sent at all. How to solve that issue?

**Comment by clarkeash** [comment]
Doorman doesn’t send emails, it just generates and redeems invite codes. It’s down to you to send the emails however you see fit. 

I have considered adding a basic email support to doorman but at this time there is no support.

**Comment by jasperf** [comment]
Sure, understood. Yeah, we will have to see how we can deal with possible bounced emails. Seems even a small code tweak, removing the email address and adding it again for a new invite did allow for another invite sendout, but Sendgrid refused again. This even though the account was receiving emai just fine. But that is an email issue. 

To have a message that the invitation email never arrived or _failure to send_ message in Doorman based on feedback from email provider would be good, but not sure how Doorman could or should help with that. Perhaps that should stay separate. Anyways, thanks for you feedback.

**Comment by clarkeash** [comment]
👍
