### ISSUE TITLE
support "ramsey/uuid": "^4.0" ?

### ISSUE THREAD

**Issue by vesper8** [clarkeash/doorman#54]
Hi there,

I'm trying to use Doorman in combination with https://github.com/michaeldyrynda/laravel-model-uuid and it's causing a collision because that package supports the latest `"ramsey/uuid": "^4.0"` and yours is tied to `^3.6`

Any chance you could add support for the `^4.0` please?

**Comment by clarkeash** [comment]
Looks like #51 will address this, I just need to check it it over

**Comment by vesper8** [comment]
Great, didn't see that PR.. hope you find the time soon as I need to make use of both libraries in a project I'm getting close to launching

many thanks!

**Comment by clarkeash** [comment]
@vesper8 yea I will take a look at this tomorrow

**Comment by clarkeash** [comment]
@vesper8 5.0.1 has been tagged with this fix

**Comment by vesper8** [comment]
Thank you @clarkeash !

For some reason I was still unable to install unless I explicitly added:

```
"ramsey/uuid": "^4.0"
```

to my composer.json

After I did that I was able to install and get everything working together on Laravel 7
