### ISSUE TITLE
How to send invite via Laravel Notifications

### ISSUE THREAD

**Issue by dominikgeimer** [clarkeash/doorman#55]
Hi,

I really like that packages, but I need some help. 

When I generate a new invite code like so. 

`Doorman::generate()->for($request->email)->expiresIn(3)->make();`

How can I send that code to the invited person ($request->email) via laravels notifications by mai?

**Comment by clarkeash** [comment]
Sorry Doorman doesnt send emails that for you to do however you see fit.
