### ISSUE TITLE
make() not to return a collection for 1 code

### ISSUE THREAD

**Issue by leenooks** [clarkeash/doorman#56]
Howdy,

Would you consider having make() not return a collection when only 1 code is created?

IE: It would be nice to be able to use ...->make()->code directly, instead of having to go ->make()->first()->code especially when only code will be made (for an email address for example).

**Comment by clarkeash** [comment]
Hi, I wouldnt really want to change `make` so that it had potentially different return types. 
But I would be happy to add a different method e.g.

```php
Doorman::generate()->for('user@example.com')->once();
```

Which would only create one invite and return that.

**Comment by clarkeash** [comment]
v5.1.0 has been released with this change https://github.com/clarkeash/doorman/releases/tag/v5.1.0
