### ISSUE TITLE
How to generate codes with unlimited uses? Is this possible?

### ISSUE THREAD

**Issue by pedrocruzlopez** [clarkeash/doorman#59]
I would like to generate one code that can be used unlimited times, is there a way to do that? Thanks in advance to anyone who can help me

**Comment by clarkeash** [comment]
Hey, I just pushed a change to make this easier. https://github.com/clarkeash/doorman/releases/tag/v5.2.0

You can do this:

```php
$invite = Doorman::generate()->unlimited()->once();
```

**Comment by pedrocruzlopez** [comment]
Thank you very much @clarkeash!
