### ISSUE TITLE
Remove Invitations

### ISSUE THREAD

**Issue by jasperf** [clarkeash/doorman#63]
We are using Doorman and it has been great. Only issue is that we sometimes want to remove the invitation and email address attached so we can re-use that email address. How could we do this the best way?

**Comment by clarkeash** [comment]
There is an eloquent model `Clarkeash\Doorman\Models\Invite` which you can use to delete the invite, or you could update it by setting the email to null.

**Comment by jasperf** [comment]
Thanks a lot for getting back to me @clarkeash . Going to look into this asap.
