### ISSUE TITLE
Non-static Method on generate()

### ISSUE THREAD

**Issue by aalicki** [clarkeash/doorman#66]
I'm using Laravel 5.8, and have installed Doorman 3.0 as per the documentation. 

When I attempt to generate an invite code using `Doorman::generate()->for($request->email)->make();`
I get an error stating **Non-static method Clarkeash\Doorman\Doorman::generate() should not be called statically**. Upon checking the class, the `generate` method is indeed not static. 

Are there any suggestions on a fix for this?

**Comment by clarkeash** [comment]
`Doorman` is a facade so it should be used on the root level.

e.g.

```php
use Doorman;

Doorman::generate()->for($request->email)->make();

```
