### ISSUE TITLE
PHP8 and composer V2

### ISSUE THREAD

**Issue by dom235** [clarkeash/doorman#68]
Good day sir and thank you very much for this nice package!

Today i was trying to upgrade a project to PHP8.

Composer (V2) complains:

clarkeash/doorman v6.0.0 requires php ^7.3 -> your php version (8.0.0) does not satisfy that requirement.

What can i do?

Thanks in advance!

**Comment by clarkeash** [comment]
Hi, doorman needs updating to support PHP 8.0 this should be a simple fix (update the GitHub build and update the composer.json) as I don't anticipate any issues with 8.0.

**Comment by dom235** [comment]
Hello Sir and thank you for your really fast reply!

I'm not that familiar with github, actions and PR's at all but i tried:

https://github.com/clarkeash/doorman/pull/69

**Comment by clarkeash** [comment]
I have tagged version 6.1.0 with php 8.0 support. Run `composer update` and you it should work for you now!

**Comment by dom235** [comment]
Lovely! It worked like a charm ❤️ Thank you so much
