### ISSUE TITLE
Invite url clicked from email hits privacy error

### ISSUE THREAD

**Issue by jasperf** [clarkeash/doorman#75]
For the first time in like error an invite link 

```
http://url5220.site.com/ls/click?upn=kvKv-2FX7KJRO-2BuIGglPGWwYFfpq-2FfmWSsrf0-.......................
```

opened from webmail loads a Chrome error page:

```
Your connection is not private
Attackers might be trying to steal your information from url5220.site.com (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_COMMON_NAME_INVALID
```
<img width="1048" alt="Screen Shot 2022-02-14 at 10 31 09 AM" src="https://user-images.githubusercontent.com/344138/153795606-81d6a446-4d93-4945-a924-5d486b87ac5e.png">

checking the certificate I see it loads the SendGrid wildcard url and not our domain wildcard url under which this "temporary" subdomain is loading.

So either the subdomain should load under SendGrid or the subdomain link is fine but it is trying to grab the wrong SSL certificate.

This could very well be an issue in our setup. Just odd it pops up now after like 2 years and wondering if anyone else has dealt with this issue.

**Comment by jasperf** [comment]
Hmm, second invite did work and redirect forward to our site to start working. No SendGrid wildcard certificate loading now. Bizarre. And still wondering why, but guess will leave issue be for now.

**Comment by clarkeash** [comment]
Doorman does not send emails, so I would expect your issue to be somewhere else.
