### ISSUE TITLE
Redeem and return redeemed invite

### ISSUE THREAD

**Issue by issa** [clarkeash/doorman#77]
I have implemented my own Driver and Invite class which are working well.

In my use case I would like to get the Invite instance after `Doorman::redeem`. Is there an easy way to get this working without me implementing my own `Doorman` class as well?

**Comment by clarkeash** [comment]
The `Invite` class is just a model so I assume by implementing your own you have a class that extends `BaseInvite` in which case you can just query as normal e.g. `YourInviteModel::where('code', '=', 'some-code')->first();` etc.

Does that help?

**Comment by issa** [comment]
Ok, that was my Plan B. So I will just `#redeem` and than the `Invite` of the same `code`.

Perhaps you are considering to return the redeemed `Invite` in a future release?
